---
title: "ESS330_lab2"
author: "Alan Cai"
date: "2025-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyverse)
```

#Import Dataset
```{r}
trees <- read.csv("data/tree_dat.csv")
```

#Q13
```{r}
trees <- trees %>%
  rename(rad_ib_mm = rad_ib, inc_mm = inc)
```

#Q14
```{r}
trees <- trees %>%
  mutate(rad_ib_cm = rad_ib_mm/10,
         DBH_cm = rad_ib_cm*2,
         BA_m2 = 0.00007854 * DBH_cm^2)

temp <- filter(trees, species == 'POTR')
temp <- filter(temp, year == 2007)

mean(temp$BA_m2)
```

#Q15
```{r}
trees %>%
  mutate(established = if_else(age > 5, TRUE, FALSE)) %>%
  count(established)
```
#Q16
```{r}
trees <- mutate(trees,
                DBH_class = case_when(
                  DBH_cm < 2.5 ~ "seedling",
                  DBH_cm >= 2.5 & DBH_cm < 10 ~ "sapling",
                  DBH_cm >= 10 & DBH_cm < 30 ~ "pole",
                  DBH_cm >= 30 ~ "sawlog")
                )

filter(trees, year == 2007) %>%
  count(DBH_class)
```



#FINAL QUESTION
```{r}
temp <- trees %>%
  group_by(treeID) %>%
  arrange(year) %>%
  mutate(growth = DBH_cm - lag(DBH_cm), 
  total_years = n()) %>%
  filter(!is.na(growth), total_years > 10) %>%
  ungroup() %>%
  group_by(species) %>%
  summarise(mean_growth = mean(growth))

slice_max(temp, mean_growth, n = 3)
slice_min(temp, mean_growth, n = 3)
  
```



